### PR TITLE
Add the branch cover helper

### PR DESCRIPTION
**Pull request by mkforsb**
See #7

### CODE REVIEW

**Review by jacobsorme — APPROVED** [review]
Yep, looks freshintosh :ok_hand: :watermelon:

**Review by maxmattila — APPROVED** [review]

**Comment by NotAFile** [comment]
What exactly is this for? Note that if this is a utility, it is in the wrong location. `piqueserver/scripts/` is for extension scripts, which this does not appear to be.

**Comment by mkforsb** [comment]
Our fork is part of a uni lab assignment on branch coverage, it's not intended to be merged with the piqueserver project.

**Comment by NotAFile** [comment]
Yep, sorry, I've received the assignment docs from another group now. I was confused because these changes landed on the master branch.

**Pull request merged**
